drop table if exists orders CASCADE;
create table orders
     (
         id   bigint generated by default as identity,
         name varchar(255),
         order_content_index int,
         primary key (id)
);